
name: Dast

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 --name web-app my-web-app

      - name: Run OWASP ZAP security scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          
    # 1. Checkout the Code
    # 2. Build the docker image localy 
    # 3. Run the docker Container
    # 4. Run OWASP ZAP on the running webserver

